name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: build-gradle
        run: ./gradlew build test install --build-cache --scan -s
      - name: build-choco-package
        if: runner.os == 'Windows'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.204' # SDK Version to use.
      - name: build-choco
        if: runner.os == 'Windows'
        run: |
            powershell
            choco pack build/choco/jbang.nuspec
      - name: Archive build results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ${{ runner.os }}-build-${{ github.sha }}
          path: build
      - name: integration-test
        if: runner.os != 'Windows'
        run: |
          export PATH=`pwd`/build/install/jbang/bin:$PATH
          cd itests
          ./test_suite.sh
  testing:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8,11,13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/download-artifact@v1
        with:
          name: ${{ runner.os }}-build-${{ github.sha }}
          path: build
      - run: |
          java -version
          chmod +x ./build/install/jbang/bin/jbang
          ./build/install/jbang/bin/jbang --init=cli helloworld.java
          ./build/install/jbang/bin/jbang helloworld.java
